<?php if (count($this->getRecommendations())): ?>
    <div class="container stacc_recommender_container" data-lang="<?php echo Mage::app()->getLocale()->getLocaleCode() ?>" data-stacc-block-time="<?php echo $this->getTimestamp();?>">
        <h2><span><?php echo $this->__('Our recommended products') ?></span></h2>
        <div class="home-categories stacc_recommender_recommendations_2">
            <ul class="products-grid stacc_recommender_recommended_products">
                <?php foreach ($this->getRecommendations() as $_link): ?>
                    <li class="item stacc_recommender_recommended_item">
                        <div class="item-image stacc_recommender_recommended_item_image">
                            <a class="product-image stacc_recommender_recommended_product_image"
                               href="<?php echo $_link->getProductUrl() ?>"
                               title="<?php echo $this->escapeHtml($_link->getName()) ?>">
                                <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(370) ?>"
                                     alt="<?php echo $this->escapeHtml($_link->getName()) ?>"
                                     title="<?php echo $this->escapeHtml($_link->getName()) ?>">
                            </a>
                            <div class="product-info stacc_recommender_recommended_product_info">
                                <h3 class="product-name stacc_recommender_recommended_product_name"><a
                                            href="<?php echo $_link->getProductUrl() ?>"
                                            title="<?php echo $this->escapeHtml($_link->getName()) ?>">
                                        <?php echo $this->escapeHtml($_link->getName()) ?>
                                    </a>
                                </h3>
                                <?php echo $this->getPriceHtml($_link, true, '-stacc_recommender') ?>
                                <span class="size-list"></span>
                            </div>
                        </div>

                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif ?>